### ISSUE TITLE
QR code generated without Bluetooth MAC addresss.

### ISSUE THREAD

**Issue by nichols-356** [pinetum/AirUnlock-for-Mac#1]
First of all, thank you for your work on this. I stumbled upon your Android app in the F-Droid catalog and figured I would give it a go. I'm currently running Mac OS 10.11.6 on a MacBookPro12,1.

I'm getting the "QR code error" message on your Android app. I looked at the code of the Android repo and saw that this error is displayed if it did not get a proper MAC address from the code. The proper format being address,key,lkey. Using a different barcode scanning application I was able to determine that the address is not being included in the QR code at all (it is showing up as [null],key,lkey). Manually creating a QR code with the MAC address, key and lkey fields allowed the connection to pass.

I found the line for the code generation [here](https://github.com/pinetum/AirUnlock-for-Mac/blob/12805ac20b352fc20863eb0e55b6fe10fe1e8cea/AirUnlock/PanelController.m#L267) (and also subsequently found that the QR code generation is logged to the Console so that could have made things slightly easier for me had I known that in advance). I'm definitely glad you included logging!

I am now installing X-code to see if I can figure this out, but I will warn you: this is my first time ever opening X-code so I can't guarantee I know what I'm doing. 👶 

If I am understanding this correctly, `NSString* btAdderss = [defaults stringForKey:@"ADDRESS"];` reads the contents of the defaults file ~/Library/Preferences/tw.qtlin.airunlock.plist (aka `defaults read tw.qtlin.airunlock ADDRESS`). As far as I can see, this was never set and there is nothing to read.

I then found the code where the ADDRESS should be set in the defaults file [here](https://github.com/pinetum/AirUnlock-for-Mac/blob/12805ac20b352fc20863eb0e55b6fe10fe1e8cea/AirUnlock/ApplicationDelegate.m#L66-L83). One thing I noticed is a discrepancy with spelling that might be throwing this off. In PanelController.m, it is "btAdderss" but in ApplicationDelegate.m, it is "btAddress". I don't know if this was intentional or if this is actually causing the issue, but maybe since ApplicationDelegate is just writing to defaults and PanelController is reading from defaults, this shouldn't matter?

**Comment by pinetum** [comment]
Do you have Bluetooth turned on?
When bluetooth is turn off, MAC address is null.
In the next release will increase the open Bluetooth prompt.
Thank you your report.
