### ISSUE TITLE
Wrong password typed in by keychain

### ISSUE THREAD

**Issue by olsiodobashi** [pinetum/AirUnlock-for-Mac#2]
Hello,
I have setup the app and on Android it works great. But everytime I try to unlock my Mac with the password stored on Keychain, it inputs the wrong password. I have made sure several times the password on keychain is the correct one and I have also tried to disable the fingerprint feature, but still the same.

Nexus 5X
macOS Sierra 10.12.2

Thanks

**Comment by pinetum** [comment]
Is the mac locked or sleeping?

**Comment by olsiodobashi** [comment]
It's sleeping (Ctrl + Shift + Power)
I have even tried to waking it before unlocking, but the same happens.

**Comment by pinetum** [comment]
The password is typed by apple script.
You can open a text editor, and press the unlock button to observe whether the words hit out with your password the same.

**Comment by 1951FDG** [comment]
I experienced this too, it was due some bugs in the code itself, the password string retrieved would be "(null)", six dots thus. I fixed this however and other bugs as well, check out my pull request: https://github.com/pinetum/AirUnlock-for-Mac/pull/4
