### ISSUE TITLE
Scanning QR code fails

### ISSUE THREAD

**Issue by jasonhemann** [pinetum/AirUnlock-for-Mac#3]
I've installed applications on both my android device and my MacBook Pro. I've paired both devices via Bluetooth, set the password and generated a QR code on my laptop. However, the scanning portion times out rather quickly, and doesn't seem to succeed. That is, the scanning ap closes very quickly and says Setting Success, but it generates a notification that says Scanning fails, make sure Mac connection within range, or re-scan QR code. 

It's difficult to line up the QR code reader precisely with the QR code on the screen, because the reader starts black and seems to take the shot immediately. However, once or twice I've managed to line it up pretty near perfectly, and it still doesn't seem to make an impact.

**Comment by Joel-Costamagna** [comment]
I have the same issue : 
it looks like it worked, and then the android app say "looking for a mac"

**Comment by pinetum** [comment]
which android phone do you use?

**Comment by jasonhemann** [comment]
@pinetum I'm using an LG G4 H811 running either CyanogenMod or LineageOS

**Comment by Joel-Costamagna** [comment]
samsung galaxy s6 edge , running android 6.0.1

**Comment by gboudreau** [comment]
I had the same issue. I experimented with the Android app codebase, and was able to make it work using [the above change](https://github.com/gboudreau/AirUnlock-for-Mac/commit/df369a76e6a1909ccd9bdcacc3b26d920117f196). I have a OnePlus 3 running Android N (7.1).

**Comment by pinetum** [comment]
Thank @gboudreau .
Do you want to make a pull request?

**Comment by gboudreau** [comment]
Just did. Not sure if this will cause issues on other devices though...

**Comment by pinetum** [comment]
@jasonhemann , @Joel-Costamagna 
I build a fix version by @gboudreau can you test ?

[Airunlock_issue_3_test.apk.zip](https://github.com/pinetum/AirUnlock-for-Mac/files/1027586/Airunlock_issue_3_test.apk.zip)


I test on my redmi note 3 RR5.8.1(android 7) have same issue, ScanCallback return a [error code 5](https://github.com/android/platform_frameworks_base/blob/nougat-mr2.1-release/core/java/android/bluetooth/le/ScanCallback.java#L51).
```java
/**
     * Fails to start scan as it is out of hardware resources.
     * @hide
     */
    public static final int SCAN_FAILED_OUT_OF_HARDWARE_RESOURCES = 5;

```

**Comment by gboudreau** [comment]
Error code 5 was what I was receiving too, without specifying `transport = BluetoothDevice.TRANSPORT_LE`.

**Comment by Quezler** [comment]
Official + above bugfix do not fix the issue on my cat s60, any suggestions?

**Comment by 1951FDG** [comment]
Hi Guys,

I just did a pull request, https://github.com/pinetum/AirUnlock-for-Android/pull/7
It may solve the issue for some of you. Also don't forget to turn Location **ON**
